# Basic
title: Leo Ten
subtitle: Death is like the wind,always by my side.
welcome_message: <a href="https://github.com/liutian0117" target="_blank">Welcome to my den.</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://www.leoten.xyz"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 2491643023?topnav=1&wvr=6&topsug=1
    github: liutian0117
    twitter: LeoHTBL
    gplus: 104709056083298303849
    mail: fjhmylove@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
