# Basic
title: Leo Ten
subtitle: Death is like the wind,always by my side.
welcome_message: <a href="https://github.com/liutian0117" target="_blank">Welcome to my den.</a>
description: 嗨，我是柳天。<br>ios开发者，现居大连。<br>商业合作请咨询女朋友。 <a href="https://weibo.com/u/5953637402" target="_blank">@三月我守口如瓶</a> 
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://www.leoten.xyz"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: white

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/liutian0117'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: tenleo
    github: liutian0117
    twitter: LeoHTBL
    gplus: 104709056083298303849
    mail: fjhmylove@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
